CC=g++
CCFLAG= -Wall -Wextra -pedantic -O2 -Wshadow -Wformat=2 -Wfloat-equal -Wconversion -Wlogical-op -Wcast-qual -Wcast-align -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -D_FORTIFY_SOURCE=2 -fsanitize=address -fsanitize=undefined -fstack-protector 
sol: 10405\ -\ Longest\ Common\ Subsequence.cpp
	$(CC) $(CCFLAG) -o sol.exe 10405\ -\ Longest\ Common\ Subsequence.cpp