CC=g++
CCFLAG= -Wall -Wextra -pedantic -O2 -Wshadow -Wformat=2 -Wfloat-equal -Wconversion -Wlogical-op -Wcast-qual -Wcast-align -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -D_FORTIFY_SOURCE=2 -fsanitize=address -fsanitize=undefined -fstack-protector 
sol: 1152\ -\ 4\ Values\ whose\ Sum\ is\ 0.cpp
	$(CC) $(CCFLAG) -o sol.exe 1152\ -\ 4\ Values\ whose\ Sum\ is\ 0.cpp